spring:
  datasource:
    url: jdbc:mysql://120.76.194.88:3306/vhr?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #Druid配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      test-on-return: true
      pool-prepared-statements: true

      #监控功能
      filter: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #   设置密码会出错
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

    lettuce:
      shutdown-timeout: 5000

  devtools:
    restart:
      enabled: true  #设置开启热部署
  #      additional-paths: src/main/java #重启目录
  #      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  mail:
    host: smtp.qq.com
    username: 953808847@qq.com
    password: vvszxrgkedzjbbdg
    default-encoding: UTF-8

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081


pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-dialect: mysql

jwt:
  secret: secret
  expiration: 120000
  token: Authorization
  refreshToken: 60000
  
  

